[en]
  title = "Clarity"
  LanguageName = "English"
  weight = 2

[zh]
title = "daidaiwo" # just for the sake of showing this is possible
LanguageName = "中文"
weight = 1


  # tip: assign the default language the lowest Weight